

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


-- CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."stripe_checkout_ticket_resum_25" (
    "id" bigint NOT NULL,
    "stripe_checkout" "text" NOT NULL,
    "email" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."stripe_checkout_ticket_resum_25" OWNER TO "postgres";


ALTER TABLE "public"."stripe_checkout_ticket_resum_25" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."stripe_checkout_ticket_resum_25_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."tickets_resum_25" (
    "id" bigint NOT NULL,
    "checkout_id" "text" NOT NULL,
    "payment_method" "text" NOT NULL,
    "code" "text" NOT NULL,
    "qr_code_sent_at" timestamp with time zone NOT NULL,
    "used_at" timestamp with time zone NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."tickets_resum_25" OWNER TO "postgres";


ALTER TABLE "public"."tickets_resum_25" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tickets_resum_25_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."stripe_checkout_ticket_resum_25"
    ADD CONSTRAINT "stripe_checkout_ticket_resum_25_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."tickets_resum_25"
    ADD CONSTRAINT "tickets_resum_25_pkey" PRIMARY KEY ("id");



ALTER TABLE "public"."stripe_checkout_ticket_resum_25" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."tickets_resum_25" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



































































































































































































GRANT ALL ON TABLE "public"."stripe_checkout_ticket_resum_25" TO "anon";
GRANT ALL ON TABLE "public"."stripe_checkout_ticket_resum_25" TO "authenticated";
GRANT ALL ON TABLE "public"."stripe_checkout_ticket_resum_25" TO "service_role";



GRANT ALL ON SEQUENCE "public"."stripe_checkout_ticket_resum_25_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."stripe_checkout_ticket_resum_25_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."stripe_checkout_ticket_resum_25_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."tickets_resum_25" TO "anon";
GRANT ALL ON TABLE "public"."tickets_resum_25" TO "authenticated";
GRANT ALL ON TABLE "public"."tickets_resum_25" TO "service_role";



GRANT ALL ON SEQUENCE "public"."tickets_resum_25_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tickets_resum_25_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tickets_resum_25_id_seq" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






























RESET ALL;
